title: Almendo Gabriel Tetelepta
logo: /assets/img/icon.jpg
description: I am an Informatics student passionate about IT, particularly in **Cyber Security** and **Web Application Development**. I enjoy combining my technical skills with effective communication, often presenting ideas and projects. I am also keenly interested in online business and how technology drives innovation in digital marketplaces.
#show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
